/** @type {import('tailwindcss').Config} */

export const COLOR_PALETTE = {
  'neutral-950': 'var(--neutral-950)',
  'neutral-900': 'var(--neutral-900)',
  'neutral-800': 'var(--neutral-800)',
  'neutral-700': 'var(--neutral-700)',
  'neutral-600': 'var(--neutral-600)',
  'neutral-500': 'var(--neutral-500)',
  'neutral-400': 'var(--neutral-400)',
  'neutral-300': 'var(--neutral-300)',
  'neutral-200': 'var(--neutral-200)',
  'neutral-100': 'var(--neutral-100)',
  'neutral-50': 'var(--neutral-50)',
  'neutral-0': 'var(--neutral-0)',

  'blue-950': 'var(--blue-950)',
  'blue-900': 'var(--blue-900)',
  'blue-800': 'var(--blue-800)',
  'blue-700': 'var(--blue-700)',
  'blue-600': 'var(--blue-600)',
  'blue-500': 'var(--blue-500)',
  'blue-400': 'var(--blue-400)',
  'blue-300': 'var(--blue-300)',
  'blue-200': 'var(--blue-200)',
  'blue-100': 'var(--blue-100)',
  'blue-50': 'var(--blue-50)',

  'orange-950': 'var(--orange-950)',
  'orange-900': 'var(--orange-900)',
  'orange-800': 'var(--orange-800)',
  'orange-700': 'var(--orange-700)',
  'orange-600': 'var(--orange-600)',
  'orange-500': 'var(--orange-500)',
  'orange-400': 'var(--orange-400)',
  'orange-300': 'var(--orange-300)',
  'orange-200': 'var(--orange-200)',
  'orange-100': 'var(--orange-100)',
  'orange-50': 'var(--orange-50)',

  'red-950': 'var(--red-950)',
  'red-900': 'var(--red-900)',
  'red-800': 'var(--red-800)',
  'red-700': 'var(--red-700)',
  'red-600': 'var(--red-600)',
  'red-500': 'var(--red-500)',
  'red-400': 'var(--red-400)',
  'red-300': 'var(--red-300)',
  'red-200': 'var(--red-200)',
  'red-100': 'var(--red-100)',
  'red-50': 'var(--red-50)',

  'green-950': 'var(--green-950)',
  'green-900': 'var(--green-900)',
  'green-800': 'var(--green-800)',
  'green-700': 'var(--green-700)',
  'green-600': 'var(--green-600)',
  'green-500': 'var(--green-500)',
  'green-400': 'var(--green-400)',
  'green-300': 'var(--green-300)',
  'green-200': 'var(--green-200)',
  'green-100': 'var(--green-100)',
  'green-50': 'var(--green-50)',

  'yellow-950': 'var(--yellow-950)',
  'yellow-900': 'var(--yellow-900)',
  'yellow-800': 'var(--yellow-800)',
  'yellow-700': 'var(--yellow-700)',
  'yellow-600': 'var(--yellow-600)',
  'yellow-500': 'var(--yellow-500)',
  'yellow-400': 'var(--yellow-400)',
  'yellow-300': 'var(--yellow-300)',
  'yellow-200': 'var(--yellow-200)',
  'yellow-100': 'var(--yellow-100)',
  'yellow-50': 'var(--yellow-50)',

  'purple-950': 'var(--purple-950)',
  'purple-900': 'var(--purple-900)',
  'purple-800': 'var(--purple-800)',
  'purple-700': 'var(--purple-700)',
  'purple-600': 'var(--purple-600)',
  'purple-500': 'var(--purple-500)',
  'purple-400': 'var(--purple-400)',
  'purple-300': 'var(--purple-300)',
  'purple-200': 'var(--purple-200)',
  'purple-100': 'var(--purple-100)',
  'purple-50': 'var(--purple-50)',

  'sky-950': 'var(--sky-950)',
  'sky-900': 'var(--sky-900)',
  'sky-800': 'var(--sky-800)',
  'sky-700': 'var(--sky-700)',
  'sky-600': 'var(--sky-600)',
  'sky-500': 'var(--sky-500)',
  'sky-400': 'var(--sky-400)',
  'sky-300': 'var(--sky-300)',
  'sky-200': 'var(--sky-200)',
  'sky-100': 'var(--sky-100)',
  'sky-50': 'var(--sky-50)',

  'pink-950': 'var(--pink-950)',
  'pink-900': 'var(--pink-900)',
  'pink-800': 'var(--pink-800)',
  'pink-700': 'var(--pink-700)',
  'pink-600': 'var(--pink-600)',
  'pink-500': 'var(--pink-500)',
  'pink-400': 'var(--pink-400)',
  'pink-300': 'var(--pink-300)',
  'pink-200': 'var(--pink-200)',
  'pink-100': 'var(--pink-100)',
  'pink-50': 'var(--pink-50)',

  'teal-950': 'var(--teal-950)',
  'teal-900': 'var(--teal-900)',
  'teal-800': 'var(--teal-800)',
  'teal-700': 'var(--teal-700)',
  'teal-600': 'var(--teal-600)',
  'teal-500': 'var(--teal-500)',
  'teal-400': 'var(--teal-400)',
  'teal-300': 'var(--teal-300)',
  'teal-200': 'var(--teal-200)',
  'teal-100': 'var(--teal-100)',
  'teal-50': 'var(--teal-50)',

  'neutral-alpha-24': 'var(--neutral-alpha-24)',
  'neutral-alpha-16': 'var(--neutral-alpha-16)',
  'neutral-alpha-10': 'var(--neutral-alpha-10)',

  'blue-alpha-24': 'var(--blue-alpha-24)',
  'blue-alpha-16': 'var(--blue-alpha-16)',
  'blue-alpha-10': 'var(--blue-alpha-10)',

  'orange-alpha-24': 'var(--orange-alpha-24)',
  'orange-alpha-16': 'var(--orange-alpha-16)',
  'orange-alpha-10': 'var(--orange-alpha-10)',

  'red-alpha-24': 'var(--red-alpha-24)',
  'red-alpha-16': 'var(--red-alpha-16)',
  'red-alpha-10': 'var(--red-alpha-10)',

  'green-alpha-24': 'var(--green-alpha-24)',
  'green-alpha-16': 'var(--green-alpha-16)',
  'green-alpha-10': 'var(--green-alpha-10)',

  'yellow-alpha-24': 'var(--yellow-alpha-24)',
  'yellow-alpha-16': 'var(--yellow-alpha-16)',
  'yellow-alpha-10': 'var(--yellow-alpha-10)',

  'purple-alpha-24': 'var(--purple-alpha-24)',
  'purple-alpha-16': 'var(--purple-alpha-16)',
  'purple-alpha-10': 'var(--purple-alpha-10)',

  'sky-alpha-24': 'var(--sky-alpha-24)',
  'sky-alpha-16': 'var(--sky-alpha-16)',
  'sky-alpha-10': 'var(--sky-alpha-10)',

  'pink-alpha-24': 'var(--pink-alpha-24)',
  'pink-alpha-16': 'var(--pink-alpha-16)',
  'pink-alpha-10': 'var(--pink-alpha-10)',

  'teal-alpha-24': 'var(--teal-alpha-24)',
  'teal-alpha-16': 'var(--teal-alpha-16)',
  'teal-alpha-10': 'var(--teal-alpha-10)',

  'white-alpha-24': 'var(--white-alpha-24)',
  'white-alpha-16': 'var(--white-alpha-16)',
  'white-alpha-10': 'var(--white-alpha-10)',

  'black-alpha-24': 'var(--black-alpha-24)',
  'black-alpha-16': 'var(--black-alpha-16)',
  'black-alpha-10': 'var(--black-alpha-10)',
};

export const TOKEN_SYSTEM = {
  primary: {
    dark: 'var(--primary-dark)',
    darker: 'var(--primary-darker)',
    base: 'var(--primary-base)',
    'alpha-16': 'var(--primary-alpha-16)',
    'alpha-10': 'var(--primary-alpha-10)',
  },
  static: {
    black: 'var(--static-black)',
    white: 'var(--static-white)',
  },
  bg: {
    strong: 'var(--bg-strong)',
    surface: 'var(--bg-surface)',
    sub: 'var(--bg-sub)',
    soft: 'var(--bg-soft)',
    weak: 'var(--bg-weak)',
    white: 'var(--bg-white)',
  },
  text: {
    strong: 'var(--text-strong)',
    sub: 'var(--text-sub)',
    soft: 'var(--text-soft)',
    disabled: 'var(--text-disabled)',
    white: 'var(--text-white)',
  },
  stroke: {
    strong: 'var(--stroke-strong)',
    sub: 'var(--stroke-sub)',
    soft: 'var(--stroke-soft)',
    white: 'var(--stroke-white)',
  },
  icon: {
    strong: 'var(--icon-strong)',
    sub: 'var(--icon-sub)',
    soft: 'var(--icon-soft)',
    disabled: 'var(--icon-disabled)',
    white: 'var(--icon-white)',
  },
  faded: {
    dark: 'var(--faded-dark)',
    base: 'var(--faded-base)',
    light: 'var(--faded-light)',
    lighter: 'var(--faded-lighter)',
  },
  information: {
    dark: 'var(--information-dark)',
    base: 'var(--information-base)',
    light: 'var(--information-light)',
    lighter: 'var(--information-lighter)',
  },
  warning: {
    dark: 'var(--warning-dark)',
    base: 'var(--warning-base)',
    light: 'var(--warning-light)',
    lighter: 'var(--warning-lighter)',
  },
  error: {
    dark: 'var(--error-dark)',
    base: 'var(--error-base)',
    light: 'var(--error-light)',
    lighter: 'var(--error-lighter)',
  },
  success: {
    dark: 'var(--success-dark)',
    base: 'var(--success-base)',
    light: 'var(--success-light)',
    lighter: 'var(--success-lighter)',
  },
  away: {
    dark: 'var(--away-dark)',
    base: 'var(--away-base)',
    light: 'var(--away-light)',
    lighter: 'var(--away-lighter)',
  },
  feature: {
    dark: 'var(--feature-dark)',
    base: 'var(--feature-base)',
    light: 'var(--feature-light)',
    lighter: 'var(--feature-lighter)',
  },
  verified: {
    dark: 'var(--verified-dark)',
    base: 'var(--verified-base)',
    light: 'var(--verified-light)',
    lighter: 'var(--verified-lighter)',
  },
  highlighted: {
    dark: 'var(--highlighted-dark)',
    base: 'var(--highlighted-base)',
    light: 'var(--highlighted-light)',
    lighter: 'var(--highlighted-lighter)',
  },
  stable: {
    dark: 'var(--stable-dark)',
    base: 'var(--stable-base)',
    light: 'var(--stable-light)',
    lighter: 'var(--stable-lighter)',
  },
};

export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './index.html',
    'node_modules/@rushable/align-ui/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: { ...TOKEN_SYSTEM, ...COLOR_PALETTE },
      screens: {
        sm: '640px', // => @media (min-width: 640px) { ... }
        md: '768px', // => @media (min-width: 768px) { ... }
        lg: '1024px', // => @media (min-width: 1024px) { ... }
        xl: '1280px', // => @media (min-width: 1280px) { ... }
        '2xl': '1536px', // => @media (min-width: 1536px) { ... }
      },
      borderRadius: {
        4: '4px',
        6: '6px',
        8: '8px',
        10: '10px',
        12: '12px',
        16: '16px',
        20: '20px',
        24: '24px',
      },
      boxShadow: {
        xs: '0px 1px 2px 0px rgba(10, 13, 20, 0.03)',
        s: '0px 2px 4px 0px rgba(27, 28, 29, 0.04)',
        m: '0px 16px 32px -12px rgba(14, 18, 27, 0.1)',
      },
    },
  },
  plugins: [],
};
